# Generated by Django 4.0.2 on 2022-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_published',
            field=models.BooleanField(default=False, null=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='tags',
            name='is_published',
            field=models.BooleanField(default=False, null=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
