# Generated by Django 4.0.2 on 2022-03-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GostSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='URL')),
                ('section_number', models.CharField(max_length=7, verbose_name='Номер раздела')),
                ('section_name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Раздел ГОСТов',
                'verbose_name_plural': 'Разделы ГОСТов',
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='GostSubSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='URL')),
                ('subsection_group', models.CharField(max_length=7, verbose_name='Номер подраздела')),
                ('subsection_name', models.CharField(max_length=255, verbose_name='Название подраздела')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gosts.gostsections', verbose_name='Раздел группы ГОСТа')),
            ],
            options={
                'verbose_name': 'Группа ГОСТов',
                'verbose_name_plural': 'Группы ГОСТов',
                'ordering': ['subsection_group'],
            },
        ),
        migrations.CreateModel(
            name='Gosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='URL')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_eng', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('standard', models.CharField(max_length=255, verbose_name='Стандарт')),
                ('standard_number', models.CharField(max_length=255, verbose_name='Номер стандарта')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gosts.gostsubsections', verbose_name='Раздел подгруппы ГОСТа')),
            ],
            options={
                'verbose_name': 'ГОСТ',
                'verbose_name_plural': 'ГОСТы',
                'ordering': ['standard_number'],
            },
        ),
    ]
