# Generated by Django 4.0.2 on 2022-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gostsections',
            options={'ordering': ['section_number'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='gostsubsections',
            options={'ordering': ['subsection_group'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='gosts',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='gosts',
            name='title_eng',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gostsections',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='gostsubsections',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
