# Generated by Django 4.0.2 on 2022-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosts', '0002_alter_gostsections_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='gosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='gostsections',
            name='is_published',
            field=models.BooleanField(default=False, null=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='gosts',
            name='standard_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер стандарта'),
        ),
        migrations.AlterField(
            model_name='gostsections',
            name='section_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='gostsections',
            name='section_number',
            field=models.CharField(max_length=7, unique=True, verbose_name='Номер раздела'),
        ),
        migrations.AlterField(
            model_name='gostsubsections',
            name='subsection_group',
            field=models.CharField(max_length=7, unique=True, verbose_name='Номер подраздела'),
        ),
        migrations.AlterField(
            model_name='gostsubsections',
            name='subsection_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название подраздела'),
        ),
    ]
