# Generated by Django 4.0.2 on 2022-03-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marochnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['name'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['pk'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='materials',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marochnik.subcategories', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marochnik.categories', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Microstructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_href', models.CharField(max_length=255, unique=True, verbose_name='URL нахождения фото')),
                ('photo_alt', models.CharField(max_length=255, verbose_name='Alt фото')),
                ('photo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание фото')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marochnik.materials', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Микроструктура',
                'verbose_name_plural': 'Микроструктуры',
                'ordering': ['pk'],
            },
        ),
    ]
