# Generated by Django 4.0.2 on 2022-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('breadcrumb_text', models.CharField(max_length=255, verbose_name='Текст хлебной крошки')),
                ('post', models.TextField(verbose_name='Текст страницы')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
